spring:
  thymeleaf:
    cache: false
  freemarker:
    expose-request-attributes: true

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hormones_base
    username: springuser
    password: 11afamet
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.yandex.ru
    username: egornesobaka@yandex.ru
    password: yjdpuigtrtophlif
    port: 465
    protocol: smtps
  sql:
    init:
      mode: always

upload:
  path: /home/egor/Документы/java/uploads

mail:
  debug: true